-- Phase 2: Enable RLS on Remaining Tables
-- Content, Reference, and Configuration Tables

BEGIN;

-- Reading Content Tables
ALTER TABLE reading_passages ENABLE ROW LEVEL SECURITY;
ALTER TABLE reading_choices ENABLE ROW LEVEL SECURITY;
ALTER TABLE reading_questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE reading_sets ENABLE ROW LEVEL SECURITY;
ALTER TABLE reading_tests ENABLE ROW LEVEL SECURITY;
ALTER TABLE reading_tests_2026 ENABLE ROW LEVEL SECURITY;
ALTER TABLE reading_test_defs ENABLE ROW LEVEL SECURITY;
ALTER TABLE reading_module_defs ENABLE ROW LEVEL SECURITY;
ALTER TABLE reading_module_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE reading_question_meta ENABLE ROW LEVEL SECURITY;
ALTER TABLE reading_results_2026 ENABLE ROW LEVEL SECURITY;

-- Listening Content Tables
ALTER TABLE listening_passages ENABLE ROW LEVEL SECURITY;
ALTER TABLE listening_questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE listening_choices ENABLE ROW LEVEL SECURITY;
ALTER TABLE listening_sets ENABLE ROW LEVEL SECURITY;
ALTER TABLE listening_tests ENABLE ROW LEVEL SECURITY;
ALTER TABLE listening_tests_2026 ENABLE ROW LEVEL SECURITY;
ALTER TABLE listening_tracks ENABLE ROW LEVEL SECURITY;
ALTER TABLE listening_results ENABLE ROW LEVEL SECURITY;
ALTER TABLE listening_results_2026 ENABLE ROW LEVEL SECURITY;

-- Naesin Content Tables
ALTER TABLE naesin_passages ENABLE ROW LEVEL SECURITY;
ALTER TABLE naesin_reading_passages ENABLE ROW LEVEL SECURITY;
ALTER TABLE naesin_reading_choices ENABLE ROW LEVEL SECURITY;
ALTER TABLE naesin_reading_questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE naesin_reading_sets ENABLE ROW LEVEL SECURITY;
ALTER TABLE naesin_reading_evidence ENABLE ROW LEVEL SECURITY;
ALTER TABLE naesin_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE naesin_contents ENABLE ROW LEVEL SECURITY;

-- Hi-Naesin Content Tables
ALTER TABLE hi_naesin_passages ENABLE ROW LEVEL SECURITY;
ALTER TABLE hi_naesin_passage_sentences ENABLE ROW LEVEL SECURITY;
ALTER TABLE hi_naesin_variant_choices ENABLE ROW LEVEL SECURITY;
ALTER TABLE hi_naesin_variant_questions ENABLE ROW LEVEL SECURITY;

-- Grammar Tables
ALTER TABLE grammar_chapters ENABLE ROW LEVEL SECURITY;
ALTER TABLE grammar_units ENABLE ROW LEVEL SECURITY;
ALTER TABLE grammar_unit_taxonomy ENABLE ROW LEVEL SECURITY;
ALTER TABLE grammar_2026_units ENABLE ROW LEVEL SECURITY;
ALTER TABLE grammar_2026_drills ENABLE ROW LEVEL SECURITY;
ALTER TABLE grammar_2026_explanation_segments ENABLE ROW LEVEL SECURITY;
ALTER TABLE grammar_2026_stylistic_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE grammar_2026_student_responses ENABLE ROW LEVEL SECURITY;
ALTER TABLE grammar_2026_unit_completions ENABLE ROW LEVEL SECURITY;

-- Vocabulary Tables
ALTER TABLE vocab_lexicon ENABLE ROW LEVEL SECURITY;
ALTER TABLE vocab_sets ENABLE ROW LEVEL SECURITY;
ALTER TABLE vocab_set_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE vocab_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE vocab_tracks ENABLE ROW LEVEL SECURITY;
ALTER TABLE vocab_track_sets ENABLE ROW LEVEL SECURITY;
ALTER TABLE vocab_track_days ENABLE ROW LEVEL SECURITY;
ALTER TABLE vocab_track_day_sets ENABLE ROW LEVEL SECURITY;
ALTER TABLE vocab_tests ENABLE ROW LEVEL SECURITY;
ALTER TABLE vocab_drill_results ENABLE ROW LEVEL SECURITY;
ALTER TABLE vocab_drill_assets ENABLE ROW LEVEL SECURITY;
ALTER TABLE vocab_drill_asset_stats ENABLE ROW LEVEL SECURITY;
ALTER TABLE voca_tests ENABLE ROW LEVEL SECURITY;
ALTER TABLE voca_results ENABLE ROW LEVEL SECURITY;
ALTER TABLE voca_passages ENABLE ROW LEVEL SECURITY;
ALTER TABLE voca_words ENABLE ROW LEVEL SECURITY;
ALTER TABLE voca_output_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE voca_word_sounds ENABLE ROW LEVEL SECURITY;
ALTER TABLE word_forms ENABLE ROW LEVEL SECURITY;
ALTER TABLE word_form ENABLE ROW LEVEL SECURITY;
ALTER TABLE word_sources ENABLE ROW LEVEL SECURITY;
ALTER TABLE word_synonyms ENABLE ROW LEVEL SECURITY;
ALTER TABLE word_grade_bands ENABLE ROW LEVEL SECURITY;
ALTER TABLE word_grammar_hints ENABLE ROW LEVEL SECURITY;
ALTER TABLE word_semantic_tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE words ENABLE ROW LEVEL SECURITY;
ALTER TABLE verb_irregular ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_word_knowledge ENABLE ROW LEVEL SECURITY;
ALTER TABLE adaptive_word_states ENABLE ROW LEVEL SECURITY;

-- Lecture Tables
ALTER TABLE lectures ENABLE ROW LEVEL SECURITY;
ALTER TABLE lecture_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE lecture_completions ENABLE ROW LEVEL SECURITY;
ALTER TABLE lecture_questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE lecture_quiz_questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE lecture_quiz_attempts ENABLE ROW LEVEL SECURITY;

-- Dictation & Speed Tables
ALTER TABLE dictations ENABLE ROW LEVEL SECURITY;
ALTER TABLE speed_attempts ENABLE ROW LEVEL SECURITY;

-- Problem Bank Tables
ALTER TABLE problem_bank_complete_words_2026 ENABLE ROW LEVEL SECURITY;
ALTER TABLE problem_bank_daily_life_2026 ENABLE ROW LEVEL SECURITY;
ALTER TABLE problem_bank_academic_passage_2026 ENABLE ROW LEVEL SECURITY;
ALTER TABLE problem_bank_listening_response_2026 ENABLE ROW LEVEL SECURITY;
ALTER TABLE problem_bank_listening_track_2026 ENABLE ROW LEVEL SECURITY;
ALTER TABLE problem_topic_tracker_2026 ENABLE ROW LEVEL SECURITY;

-- User Listening Sets & Word Knowledge
ALTER TABLE user_listening_sets ENABLE ROW LEVEL SECURITY;

-- Content Sets
ALTER TABLE content_sets ENABLE ROW LEVEL SECURITY;
ALTER TABLE contents ENABLE ROW LEVEL SECURITY;

-- Photo Homework
ALTER TABLE photo_homework ENABLE ROW LEVEL SECURITY;
ALTER TABLE photo_homework_submissions ENABLE ROW LEVEL SECURITY;

-- Answers & Choices (General)
ALTER TABLE answers ENABLE ROW LEVEL SECURITY;
ALTER TABLE choices ENABLE ROW LEVEL SECURITY;
ALTER TABLE answer_key ENABLE ROW LEVEL SECURITY;

-- Quiz & Test Template Tables
ALTER TABLE sets ENABLE ROW LEVEL SECURITY;
ALTER TABLE passages ENABLE ROW LEVEL SECURITY;
ALTER TABLE questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE explanations ENABLE ROW LEVEL SECURITY;

-- Misc Tables
ALTER TABLE popup_quiz_results ENABLE ROW LEVEL SECURITY;
ALTER TABLE perk_redemptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE student_point_ledger ENABLE ROW LEVEL SECURITY;
ALTER TABLE student_prescriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE student_skill_summaries ENABLE ROW LEVEL SECURITY;
ALTER TABLE teacher_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE teacher_warnings ENABLE ROW LEVEL SECURITY;
ALTER TABLE homework_reminders ENABLE ROW LEVEL SECURITY;
ALTER TABLE notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE passage_grammar_targets ENABLE ROW LEVEL SECURITY;
ALTER TABLE student_avatars ENABLE ROW LEVEL SECURITY;
ALTER TABLE student_gamification ENABLE ROW LEVEL SECURITY;
ALTER TABLE student_parent_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE student_unit_progress ENABLE ROW LEVEL SECURITY;
ALTER TABLE student_naesin_reading_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE test_retake_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE student_schedule_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE lexiox_jr_passage_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE lexiox_jr_drill_results ENABLE ROW LEVEL SECURITY;

-- Additional Naesin Tables
ALTER TABLE naesin_exam_schedule ENABLE ROW LEVEL SECURITY;
ALTER TABLE naesin_exam_scope_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE naesin_exam_scopes ENABLE ROW LEVEL SECURITY;

-- Vocabb Misc
ALTER TABLE vocab_student_goals ENABLE ROW LEVEL SECURITY;
ALTER TABLE vocab_homework ENABLE ROW LEVEL SECURITY;
ALTER TABLE vocab_import_batches ENABLE ROW LEVEL SECURITY;
ALTER TABLE vocab_import_batch_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE vocab_assignment_notices ENABLE ROW LEVEL SECURITY;
ALTER TABLE vocab_learning_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE vocab_weak_state ENABLE ROW LEVEL SECURITY;
ALTER TABLE vocab_set_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE vocab_set_words ENABLE ROW LEVEL SECURITY;
ALTER TABLE vocab_word_strength ENABLE ROW LEVEL SECURITY;
ALTER TABLE vocab_daily_points ENABLE ROW LEVEL SECURITY;

-- TOEFL Platform
ALTER TABLE toefl_chapters ENABLE ROW LEVEL SECURITY;
ALTER TABLE toefl_chapter_content ENABLE ROW LEVEL SECURITY;
ALTER TABLE toefl_student_level ENABLE ROW LEVEL SECURITY;
ALTER TABLE toefl_student_progress ENABLE ROW LEVEL SECURITY;
ALTER TABLE toefl_level_results ENABLE ROW LEVEL SECURITY;

-- Misc Config
ALTER TABLE perk_catalog ENABLE ROW LEVEL SECURITY;
ALTER TABLE point_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE semantic_tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE ui_label_catalog ENABLE ROW LEVEL SECURITY;
ALTER TABLE video_assets ENABLE ROW LEVEL SECURITY;
ALTER TABLE textbook_lesson_grammar_map ENABLE ROW LEVEL SECURITY;
ALTER TABLE learning_targets ENABLE ROW LEVEL SECURITY;
ALTER TABLE learning_stage_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE learning_stage_attempts ENABLE ROW LEVEL SECURITY;
ALTER TABLE learning_stage_flags ENABLE ROW LEVEL SECURITY;
ALTER TABLE jr_reading_passages ENABLE ROW LEVEL SECURITY;
ALTER TABLE jr_reading_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE jr_grammar_chapters ENABLE ROW LEVEL SECURITY;
ALTER TABLE jr_listening_audio ENABLE ROW LEVEL SECURITY;
ALTER TABLE jr_listening_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE jr_speaking_writing_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE middle_naesin_contents ENABLE ROW LEVEL SECURITY;
ALTER TABLE middle_naesin_units ENABLE ROW LEVEL SECURITY;
ALTER TABLE ranking_snapshots ENABLE ROW LEVEL SECURITY;
ALTER TABLE content_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE test_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE popup_quizzes ENABLE ROW LEVEL SECURITY;
ALTER TABLE reading_attempt_answers ENABLE ROW LEVEL SECURITY;
ALTER TABLE generated_exams ENABLE ROW LEVEL SECURITY;
ALTER TABLE generated_exam_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE generated_exam_responses ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_usage_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE test_assignment_groups ENABLE ROW LEVEL SECURITY;
ALTER TABLE site_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE speaking_tests ENABLE ROW LEVEL SECURITY;
ALTER TABLE speaking_results_2026 ENABLE ROW LEVEL SECURITY;
ALTER TABLE speaking_rounds ENABLE ROW LEVEL SECURITY;
ALTER TABLE speaking_voca_drill_results ENABLE ROW LEVEL SECURITY;
ALTER TABLE writing_tests ENABLE ROW LEVEL SECURITY;

COMMIT;
